const languages = {
  "2048.CanotSwitchGameMode": "当前无法切换游戏模式",
  "basetable.BalanceNotEnough": "余额不足",
  "basetable.ChangeGradeWarning": "房主修改了游戏设置，请重新准备！",
  "basetable.ChangeJoinFeeGradeBy0Seat": "只有0号位可调整场次",
  "basetable.IllegalParameter": "非法参数",
  "basetable.cancel_deposit_error": "取消托管失败",
  "basetable.deposit_error": "托管失败",
  "basetable.escape": "提前离开游戏",
  "basetable.fail": "游戏失败",
  "basetable.is_gaming": "游戏进行中",
  "basetable.mate_agree_error": "申请人已经不在房间",
  "basetable.mate_apply_repeat": "您已申请上麦旁观,请耐心等待",
  "basetable.not_start_game": "这位用户不能开始游戏",
  "basetable.seat": "房间内座位已满",
  "basetable.server_timeout": "请求处理超时",
  "basetable.start_condition_not_enough": "开始游戏条件不足",
  "basetable.user_exists": "这位用户已经进房了",
  "basetable.user_not_exists": "这位用户不在房间中",
  "basetable.version": "客户端版本过低",
  "basetable.victory": "游戏胜利",
  "big_two.cancel_deposit_error": "取消托管失败",
  "big_two.deposit_error": "托管失败",
  "big_two.game_status_error": "当前游戏状态不对",
  "big_two.no_card_exist_error": "你出的牌不存在",
  "big_two.out_card_error": "你出的牌不符合游戏规则",
  "big_two.out_card_success": "出牌成功",
  "big_two.turn_user_error": "还没轮到这位用户出牌",
  "big_two.user_not_exists": "这位用户没有上麦",
  "butt.game_not_start": "游戏还未开始",
  "butt.in_cooling_time": "还在冷却中",
  "butt.no_enough_space": "没有足够的空间",
  "butt.track_un_exist": "该跑道不存在",
  "cubeboom.Error_InvalidAction": "当前阶段操作无效",
  "cubeboom.Error_InvalidEnemy": "所选敌人无效",
  "cubeboom.Error_InvalidExchange": "无效交换",
  "cubeboom.Error_RoundAction": "不是你的回合",
  "domino.cancel_deposit_error": "取消托管失败",
  "domino.deposit_error": "托管失败",
  "domino.game_status_error": "当前游戏状态不对",
  "domino.no_card_exist_error": "你出的牌不存在",
  "domino.out_card_error": "你出的牌不符合游戏规则",
  "domino.out_card_success": "出牌成功",
  "domino.turn_user_error": "还没轮到这位用户出牌",
  "domino.user_not_exists": "这位用户没有上麦",
  "dummy.already_show_card_error": "这位玩家已经秀过牌",
  "dummy.can_not_draw_card_error": "牌堆中没有牌了",
  "dummy.can_not_show_card_error": "这位玩家不能秀牌",
  "dummy.game_status_error": "当前游戏状态不对",
  "dummy.out_card_error": "出牌不符合规则",
  "dummy.turn_user_error": "还没轮到这位用户出牌",
  "dummy.user_not_exists": "这位用户没有上麦",
  "dummy.user_op_error": "玩家操作有误",
  "gamework.failed": "开启失败，请稍后重试",
  "gamework.no_privilege": "权限不够",
  "gamework.room_exist_other_widget": "房间已开启了其他插件",
  "gamework.room_info_is_not_exist": "房间信息或用户信息不存在",
  "gamework.success": "成功",
  "gamework.widget_game_is_not_opened": "游戏未开启，等房主开启插件",
  "gamework.widget_game_is_opened": "游戏已开启",
  "garden.dig_up_land_err": "开垦土地失败",
  "garden.fetch_harvest_err": "收获失败",
  "garden.flower_had_water": "已浇过水",
  "garden.flower_no_enough": "所剩不多了，请给主人留点",
  "garden.flower_state_mature": "花已成熟，不用浇水",
  "garden.get_land_view_err": "获取土地信息失败",
  "garden.get_user_game_info_err": "查询用户等级信息失败",
  "garden.init_land_empty": "初始化土地为空",
  "garden.init_land_error": "初始化土地失败",
  "garden.purchase_flower_err": "购买花朵失败",
  "garden.put_water_err": "浇水失败",
  "garden.user_need_follow_err": "动动手指就能关注偷东西了",
  "garden.user_water_err": "未关注该玩家，不能帮忙浇水",
  "gf.gvalid.rule.__default__": ":attribute 字段值不合法",
  "gf.gvalid.rule.array": ":attribute 字段应当为数组",
  "gf.gvalid.rule.bank-card": ":attribute 银行卡号格式不正确",
  "gf.gvalid.rule.between": ":attribute 字段大小为:min到:max",
  "gf.gvalid.rule.boolean": ":attribute 字段应当为布尔值",
  "gf.gvalid.rule.date": ":attribute 日期格式不正确",
  "gf.gvalid.rule.date-format": ":attribute 日期格式不满足:format",
  "gf.gvalid.rule.different": ":attribute 字段值不能与:field相同",
  "gf.gvalid.rule.domain": ":attribute 域名格式不正确",
  "gf.gvalid.rule.email": ":attribute 邮箱地址格式不正确",
  "gf.gvalid.rule.float": ":attribute 字段应当为浮点数",
  "gf.gvalid.rule.in": ":attribute 字段值不合法",
  "gf.gvalid.rule.integer": ":attribute 字段应当为整数",
  "gf.gvalid.rule.ip": ":attribute IP地址格式不正确",
  "gf.gvalid.rule.ipv4": ":attribute IPv4地址格式不正确",
  "gf.gvalid.rule.ipv6": ":attribute IPv6地址格式不正确",
  "gf.gvalid.rule.json": ":attribute 字段应当为JSON格式",
  "gf.gvalid.rule.length": ":attribute 字段长度为:min到:max个字符",
  "gf.gvalid.rule.mac": ":attribute MAC地址格式不正确",
  "gf.gvalid.rule.max": ":attribute 字段最大值为:max",
  "gf.gvalid.rule.max-length": ":attribute 字段最大长度为:max",
  "gf.gvalid.rule.min": ":attribute 字段最小值为:min",
  "gf.gvalid.rule.min-length": ":attribute 字段最小长度为:min",
  "gf.gvalid.rule.not-in": ":attribute 字段值不合法",
  "gf.gvalid.rule.passport": ":attribute 账号格式不合法，必需以字母开头，只能包含字母、数字和下划线，长度在6~18之间",
  "gf.gvalid.rule.password": ":attribute 密码格式不合法，密码格式为任意6-18位的可见字符",
  "gf.gvalid.rule.password2": ":attribute 密码格式不合法，密码格式为任意6-18位的可见字符，必须包含大小写字母和数字",
  "gf.gvalid.rule.password3": ":attribute 密码格式不合法，密码格式为任意6-18位的可见字符，必须包含大小写字母、数字和特殊字符",
  "gf.gvalid.rule.phone": ":attribute 手机号码格式不正确",
  "gf.gvalid.rule.phone-loose": ":attribute 手机号码格式不正确",
  "gf.gvalid.rule.postcode": ":attribute 邮政编码不正确",
  "gf.gvalid.rule.qq": ":attribute QQ号码格式不正确",
  "gf.gvalid.rule.regex": ":attribute 字段值不合法",
  "gf.gvalid.rule.required": ":attribute 字段不能为空",
  "gf.gvalid.rule.required-if": ":attribute 字段不能为空",
  "gf.gvalid.rule.required-unless": ":attribute 字段不能为空",
  "gf.gvalid.rule.required-with": ":attribute 字段不能为空",
  "gf.gvalid.rule.required-with-all": ":attribute 字段不能为空",
  "gf.gvalid.rule.required-without": ":attribute 字段不能为空",
  "gf.gvalid.rule.required-without-all": ":attribute 字段不能为空",
  "gf.gvalid.rule.resident-id": ":attribute 身份证号码格式不正确",
  "gf.gvalid.rule.same": ":attribute 字段值必须和:field相同",
  "gf.gvalid.rule.telephone": ":attribute 电话号码格式不正确",
  "gf.gvalid.rule.url": ":attribute URL地址格式不正确",
  "gf.gvalid.rule.xml": ":attribute 字段应当为XML格式",
  "gobang.can_not_put_this_pos": "棋子不能放置在该位置",
  "gobang.game_not_start": "游戏还未开始",
  "gobang.not_your_round": "不是你的回合",
  "kittens.can_not_draw_card_error": "牌堆中没有牌了",
  "kittens.game_status_error": "当前游戏状态不对",
  "kittens.out_card_error": "出牌不符合规则",
  "kittens.turn_user_error": "还没轮到这位用户操作",
  "kittens.user_have_knocked_out": "玩家已被淘汰",
  "kittens.user_op_error": "玩家操作有误",
  "landlord.cancel_deposit_error": "取消托管失败",
  "landlord.deposit_error": "托管失败",
  "landlord.game_status_error": "当前游戏状态不对",
  "landlord.no_card_exist_error": "你出的牌不存在",
  "landlord.out_card_error": "你出的牌不符合游戏规则",
  "landlord.out_card_success": "出牌成功",
  "landlord.turn_user_error": "还没轮到这位用户出牌",
  "landlord.user_not_exists": "这位用户没有上麦",
  "ludo.cancel_deposit_error": "取消托管失败",
  "ludo.deposit_error": "托管失败",
  "ludo.diamond_not_enough": "鑽石數量不足",
  "ludo.game_status_error": "当前游戏状态不对",
  "ludo.gold_not_enough": "金豆數量不足",
  "ludo.not_exist_movable_chess": "没有可移动的棋子",
  "ludo.roll_again": "再摇一次",
  "ludo.shop_buy_failed": "购买皮肤失败",
  "ludo.shop_use_failed": "使用皮肤失败",
  "ludo.take_effect_next": "装扮将在下一局生效",
  "ludo.timeout_once": "您已经超时一次，再次超时将被托管",
  "ludo.user_not_exists": "这位用户没有上麦",
  "mahjong-tw.game_status_error": "当前游戏状态不对",
  "mahjong-tw.no_card_exist_error": "当前出的牌不存在",
  "mahjong-tw.others_can_operate": "其他玩家可操作，需等待其他玩家操作完",
  "mahjong-tw.out_card_error": "出牌不符合规则",
  "mahjong-tw.turn_user_error": "未轮到当前用户出牌",
  "mahjong-tw.user_already_ting": "玩家已听牌",
  "mahjong-tw.user_operate_error": "玩家操作错误",
  "mahjong-tw.user_ting_error": "听牌失败",
  "monopoly.invalid_operate": "无效操作",
  "monopoly.invalid_state": "游戏状态不正确",
  "monopoly.money_not_enough": "金钱不足",
  "richman.add_new_event_is_failed": "新增事件失败，请稍后再试",
  "richman.event_be_forbidden": "事件被禁止",
  "richman.map_lists_can_not_find_map": "地图列表找不到对应的地图",
  "richman.map_name_is_existed": "地图名称已存在",
  "richman.map_name_is_too_long": "地图名称太长",
  "richman.map_notice_is_too_long": "地图公告太长",
  "richman.user_already_in_line": "用户已在队列中",
  "richman.user_line_do_not_find_user": "排队列表中没有找到对应的用户",
  "room_match.cancel_match_fail": "取消匹配失败",
  "room_match.is_matching": "匹配中",
  "room_match.is_not_match_start": "匹配未开始",
  "room_match.match_fail": "匹配失败",
  "room_match.no_match_type": "未选择游戏类型",
  "room_match.not_owner": "非房主无权限",
  "sevens.no_card_exist_error": "你出的牌不存在",
  "sevens.out_card_error": "你出的牌不符合游戏规则",
  "sevens.user_have_cards_can_out": "有牌可出，不能盖牌",
  "system.need_login": "需要登录验证才能继续操作",
  "system.param_error": "参数错误",
  "truco.can_not_show_card_error": "当前不能秀牌",
  "truco.game_status_error": "当前游戏状态不对",
  "truco.out_card_error": "出牌不符合规则",
  "truco.turn_user_error": "还没轮到这位用户出牌",
  "truco.user_op_error": "玩家操作有误",
  "uno.cancel_deposit_error": "取消托管失败",
  "uno.card_num_error": "牌数不对",
  "uno.deposit_error": "托管失败",
  "uno.discard_error": "不是这位用户出牌",
  "uno.game_status_error": "当前游戏状态不对",
  "uno.no_card_exist_error": "你出的牌不存在",
  "uno.out_card_error": "你出的牌不符合游戏规则",
  "uno.out_card_success": "出牌成功",
  "uno.turn_user_error": "还没轮到这位用户出牌",
  "uno.user_not_exists": "这位用户没有上麦",
  "veekaconsume.GameBet": "下注",
  "veekaconsume.GameBuy": "购买",
  "veekaconsume.GameChangeCards": "换牌",
  "veekaconsume.GameGift": "礼物",
  "veekaconsume.GameRebase": "下注返还",
  "veekaconsume.GameSettle": "结算",
  "wolf.is_gaming": "游戏进行中",
  "wolf.mode_no_need_change": "游戏模式无需选择",
  "wolf.other_site_not_empty": "非游戏麦位不为空",
  "wolf.role_card_num_empty": "身份卡余额不足哦",
  "wolf.turn_user_error": "还没轮到该用户操作",
  "wolf.user_already_op_error": "已操作过了",
  "wolf.user_already_vote_error": "已投过票了",
  "wolf.user_checked_error": "已查验过该玩家了",
  "wolf.user_op_error": "玩家操作有误",
  "wolf.user_select_error": "选择有误"
};
export const server_zh_CN = languages;